package api;

import java.io.Serializable;

/**
 * A product is a product which can be added or modified by administrator or
 * added to shopping cart by shopper or bought by customer. Its information
 * includes:
 * <ul>
 * <li>its name
 * <li>the category it belongs to
 * <li>its price
 * <li>An ID generated by system
 * <li>its total quantity
 * </ul>
 * 
 * @author Derek
 * @version 1.0
 *
 */

public class Product implements Serializable {
	/**
	 * its name is a string
	 */
	protected String prodName;
	/**
	 * belongs to a category which is a Category
	 */
	protected Category category;
	/**
	 * its price is a double
	 */
	protected double price;
	/**
	 * A code stores the Id
	 */
	protected static int code = 0;
	/**
	 * An ID which generated sequentially
	 */
	protected int ID;
	/**
	 * its total quantity
	 */
	protected int quantity;

	/**
	 * product image
	 */
	protected String imagePath;
	
	/**
	 * product description
	 */
	protected String description;
	
	/**
	 * This method must return a new product
	 * 
	 * @param prodName the product name 
	 * @param category the category of the product
	 * @param price the price of the product
	 */
	public Product(String prodName, Category category, double price) {
		this.category = category;
		this.price = price;
		this.prodName = prodName;
		code++;
		ID = code;
		quantity = 0;

	}

	/**
	 * Adds the quantity of the product form the initial quantity.
	 *
	 * @param num
	 *            the quantity to be added
	 */
	public void addQuantity(int num) {
		this.quantity = this.quantity + num;
	}

	/**
	 * Subtracts the quantity of the product from the initial quantity.
	 *
	 * @param num
	 *            the quantity to be subtracted
	 */
	public void subQuantity(int num) {
		this.quantity = this.quantity - num;
	}
	
	/**
	 * a string representation of the product
	 * @return this Product
	 */

	public String toString() {
		return ID + " " + this.prodName + " " + this.category;
	}

}
